name: PR checks
on:
  pull_request:
  workflow_dispatch:
jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm i --ignore-scripts

      - name: Run ESLint
        run: npm run lint